services:
  db:
    image: postgres:15
    container_name: healthai_db_dev
    environment:
      POSTGRES_DB: healthai_db
      POSTGRES_USER: healthai
      POSTGRES_PASSWORD: healthai_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
