services:
  db:
    image: postgres:15
    container_name: healthai_db_dev
    environment:
      POSTGRES_DB: healthai_db
      POSTGRES_USER: healthai
      POSTGRES_PASSWORD: healthai_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: healthai_api
    depends_on:
      - db
    env_file: .env

    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  metabase:
    image: metabase/metabase:latest
    container_name: healthai_metabase
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: db
      MB_DB_PORT: 5432
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
