"""Initial migration

Revision ID: 0d1e2e25e372
Revises:
Create Date: 2026-04-09 16:16:42.221783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "0d1e2e25e372"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a sequence for id_exercice
    op.execute("CREATE SEQUENCE exercice_id_exercice_seq START 1")
    # Add id_exercice column with the sequence as default (add as nullable first to handle existing rows)
    op.add_column("exercice", sa.Column("id_exercice", sa.Integer(), nullable=True))
    # Populate current rows using the sequence
    op.execute(
        "UPDATE exercice SET id_exercice = nextval('exercice_id_exercice_seq') WHERE id_exercice IS NULL"
    )
    # Make it non-nullable and add server default
    op.alter_column(
        "exercice",
        "id_exercice",
        nullable=False,
        server_default=text("nextval('exercice_id_exercice_seq'::regclass)"),
    )
    # Add other new columns
    op.add_column(
        "exercice", sa.Column("difficulte", sa.String(length=50), nullable=True)
    )
    op.add_column("exercice", sa.Column("instructions", sa.Text(), nullable=True))
    # Alter column types
    op.alter_column(
        "exercice",
        "nom",
        existing_type=sa.TEXT(),
        type_=sa.String(length=150),
        nullable=False,
    )
    op.alter_column(
        "exercice",
        "type_exercice",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        nullable=False,
    )
    op.alter_column(
        "exercice",
        "muscles_principaux",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "exercice",
        "muscles_secondaires",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "exercice",
        "equipement",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # Create primary key on id_exercice for foreign key constraint to work
    op.create_primary_key("exercice_pkey", "exercice", ["id_exercice"])
    op.create_foreign_key(
        None, "log_seance", "exercice", ["id_exercice"], ["id_exercice"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "log_seance", type_="foreignkey")
    op.drop_constraint("exercice_pkey", "exercice", type_="primary")
    op.drop_column("exercice", "instructions")
    op.drop_column("exercice", "difficulte")
    op.drop_column("exercice", "id_exercice")
    op.execute("DROP SEQUENCE IF EXISTS exercice_id_exercice_seq")
    op.alter_column(
        "exercice",
        "equipement",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "exercice",
        "muscles_secondaires",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "exercice",
        "muscles_principaux",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "exercice",
        "type_exercice",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "exercice",
        "nom",
        existing_type=sa.String(length=150),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.drop_column("exercice", "instructions")
    op.drop_column("exercice", "difficulte")
    op.drop_column("exercice", "id_exercice")
    # ### end Alembic commands ###
