"""Initial migration

Revision ID: 1b1a5a6b1c3b
Revises:
Create Date: 2026-03-22 16:37:30.217457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b1a5a6b1c3b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aliment",
        sa.Column("id_aliment", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("calories", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("proteines", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("lipides", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("glucides", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column(
            "unite_mesure", sa.String(length=20), server_default="100g", nullable=True
        ),
        sa.PrimaryKeyConstraint("id_aliment"),
    )
    op.create_index(
        op.f("ix_aliment_id_aliment"), "aliment", ["id_aliment"], unique=False
    )
    op.create_table(
        "exercice",
        sa.Column("id_exercice", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=150), nullable=False),
        sa.Column("type_exercice", sa.String(length=100), nullable=False),
        sa.Column("muscle_cible", sa.String(length=100), nullable=True),
        sa.Column("equipement", sa.String(length=100), nullable=True),
        sa.Column("difficulte", sa.String(length=50), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id_exercice"),
    )
    op.create_index(
        op.f("ix_exercice_id_exercice"), "exercice", ["id_exercice"], unique=False
    )
    op.create_table(
        "utilisateur",
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=50), nullable=False),
        sa.Column("prenom", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("date_de_naissance", sa.Date(), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("objectif_principal", sa.String(length=200), nullable=False),
        sa.Column("poids_actuel", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("taille_cm", sa.Integer(), nullable=False),
        sa.Column(
            "type_abonnement",
            sa.String(length=50),
            server_default="Freemium",
            nullable=True,
        ),
        sa.Column(
            "date_inscription",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("mot_de_passe_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id_utilisateur"),
    )
    op.create_index(op.f("ix_utilisateur_email"), "utilisateur", ["email"], unique=True)
    op.create_index(
        op.f("ix_utilisateur_id_utilisateur"),
        "utilisateur",
        ["id_utilisateur"],
        unique=False,
    )
    op.create_table(
        "log_aliment",
        sa.Column("id_log_aliment", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("repas", sa.String(length=50), nullable=False),
        sa.Column("quantite_g", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("id_aliment", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_aliment"],
            ["aliment.id_aliment"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"], ["utilisateur.id_utilisateur"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_log_aliment"),
    )
    op.create_index(
        op.f("ix_log_aliment_id_log_aliment"),
        "log_aliment",
        ["id_log_aliment"],
        unique=False,
    )
    op.create_table(
        "log_sante",
        sa.Column("id_log_sante", sa.Integer(), nullable=False),
        sa.Column(
            "date_log",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("poids_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("moyenne_bpm", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("heures_sommeil", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("nb_pas", sa.Integer(), nullable=True),
        sa.Column("frequence_cardiaque", sa.Integer(), nullable=True),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"], ["utilisateur.id_utilisateur"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_log_sante"),
    )
    op.create_index(
        op.f("ix_log_sante_id_log_sante"), "log_sante", ["id_log_sante"], unique=False
    )
    op.create_table(
        "log_seance",
        sa.Column("id_seance_log", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("duree_exercice", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("calorie_brulee", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("id_exercice", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_exercice"],
            ["exercice.id_exercice"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"], ["utilisateur.id_utilisateur"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_seance_log"),
    )
    op.create_index(
        op.f("ix_log_seance_id_seance_log"),
        "log_seance",
        ["id_seance_log"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_seance_id_seance_log"), table_name="log_seance")
    op.drop_table("log_seance")
    op.drop_index(op.f("ix_log_sante_id_log_sante"), table_name="log_sante")
    op.drop_table("log_sante")
    op.drop_index(op.f("ix_log_aliment_id_log_aliment"), table_name="log_aliment")
    op.drop_table("log_aliment")
    op.drop_index(op.f("ix_utilisateur_id_utilisateur"), table_name="utilisateur")
    op.drop_index(op.f("ix_utilisateur_email"), table_name="utilisateur")
    op.drop_table("utilisateur")
    op.drop_index(op.f("ix_exercice_id_exercice"), table_name="exercice")
    op.drop_table("exercice")
    op.drop_index(op.f("ix_aliment_id_aliment"), table_name="aliment")
    op.drop_table("aliment")
    # ### end Alembic commands ###
