"""Ajout eau aliment

Revision ID: 23df462e9ef6
Revises: 0d1e2e25e372
Create Date: 2026-04-09 16:25:49.044744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23df462e9ef6'
down_revision: Union[str, Sequence[str], None] = '0d1e2e25e372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliment', sa.Column('eau_ml', sa.Numeric(precision=7, scale=2), nullable=True))
    op.create_index(op.f('ix_exercice_id_exercice'), 'exercice', ['id_exercice'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercice_id_exercice'), table_name='exercice')
    op.drop_column('aliment', 'eau_ml')
    # ### end Alembic commands ###
