"""water units refactoring - liters to milliliters

Revision ID: 4279a143b14f
Revises: 555f5e9e3276
Create Date: 2026-04-10 11:31:47.307086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4279a143b14f"
down_revision: Union[str, Sequence[str], None] = "555f5e9e3276"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - convert water units from liters to milliliters."""
    # ### commands auto generated by Alembic - please adjust! ###

    # dataset_historique_seance_exercice: add consommation_eau_ml and drop consommation_eau_l
    op.add_column(
        "dataset_historique_seance_exercice",
        sa.Column(
            "consommation_eau_ml", sa.Numeric(precision=7, scale=2), nullable=True
        ),
    )
    op.drop_column("dataset_historique_seance_exercice", "consommation_eau_l")

    # dataset_historique_seance_exercice_import_anomalies: add consommation_eau_ml and drop consommation_eau_l
    op.add_column(
        "dataset_historique_seance_exercice_import_anomalies",
        sa.Column(
            "consommation_eau_ml", sa.Numeric(precision=7, scale=2), nullable=True
        ),
    )
    op.drop_column(
        "dataset_historique_seance_exercice_import_anomalies", "consommation_eau_l"
    )

    # log_sante: add hydratation_ml and drop hydratation_litres
    op.add_column(
        "log_sante",
        sa.Column("hydratation_ml", sa.Numeric(precision=7, scale=2), nullable=True),
    )
    op.drop_column("log_sante", "hydratation_litres")

    # profil_sante: change heures_entrainement_semaine to Numeric type
    op.alter_column(
        "profil_sante",
        "heures_entrainement_semaine",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=4, scale=1),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert profil_sante
    op.alter_column(
        "profil_sante",
        "heures_entrainement_semaine",
        existing_type=sa.Numeric(precision=4, scale=1),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )

    # Revert log_sante
    op.add_column(
        "log_sante",
        sa.Column(
            "hydratation_litres",
            sa.Numeric(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("log_sante", "hydratation_ml")

    # Revert dataset_historique_seance_exercice_import_anomalies
    op.add_column(
        "dataset_historique_seance_exercice_import_anomalies",
        sa.Column(
            "consommation_eau_l",
            sa.Numeric(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column(
        "dataset_historique_seance_exercice_import_anomalies", "consommation_eau_ml"
    )

    # Revert dataset_historique_seance_exercice
    op.add_column(
        "dataset_historique_seance_exercice",
        sa.Column(
            "consommation_eau_l",
            sa.Numeric(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("dataset_historique_seance_exercice", "consommation_eau_ml")
    # ### end Alembic commands ###
