"""update profil_sante schema

Revision ID: 555f5e9e3276
Revises: 7a750fef47b6
Create Date: 2026-04-10 11:22:17.863163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "555f5e9e3276"
down_revision: Union[str, Sequence[str], None] = "7a750fef47b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profil_sante",
        sa.Column("heures_entrainement_semaine", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "profil_sante",
        "experience_sportive",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.drop_column("profil_sante", "frequence_entrainement")
    op.drop_column("profil_sante", "niveau_activite")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profil_sante",
        sa.Column(
            "niveau_activite", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "profil_sante",
        sa.Column(
            "frequence_entrainement",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "profil_sante",
        "experience_sportive",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("profil_sante", "heures_entrainement_semaine")
    # ### end Alembic commands ###
