"""Add import anomalies tables

Revision ID: 65ac16a6dd0c
Revises: 1b1a5a6b1c3b
Create Date: 2026-03-26 18:37:18.795734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65ac16a6dd0c"
down_revision: Union[str, Sequence[str], None] = "1b1a5a6b1c3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aliment_import_anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=1000), nullable=True),
        sa.Column("calories", sa.String(length=1000), nullable=True),
        sa.Column("proteines", sa.String(length=1000), nullable=True),
        sa.Column("lipides", sa.String(length=1000), nullable=True),
        sa.Column("glucides", sa.String(length=1000), nullable=True),
        sa.Column("unite_mesure", sa.String(length=1000), nullable=True),
        sa.Column("erreur", sa.Text(), nullable=False),
        sa.Column(
            "est_corrige", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "date_import",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aliment_import_anomalies_id"),
        "aliment_import_anomalies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "exercice_import_anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=1000), nullable=True),
        sa.Column("type_exercice", sa.String(length=1000), nullable=True),
        sa.Column("muscle_cible", sa.String(length=1000), nullable=True),
        sa.Column("equipement", sa.String(length=1000), nullable=True),
        sa.Column("difficulte", sa.String(length=1000), nullable=True),
        sa.Column("instructions", sa.String(length=1000), nullable=True),
        sa.Column("erreur", sa.Text(), nullable=False),
        sa.Column(
            "est_corrige", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "date_import",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercice_import_anomalies_id"),
        "exercice_import_anomalies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "utilisateur_import_anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=1000), nullable=True),
        sa.Column("prenom", sa.String(length=1000), nullable=True),
        sa.Column("email", sa.String(length=1000), nullable=True),
        sa.Column("date_de_naissance", sa.String(length=1000), nullable=True),
        sa.Column("genre", sa.String(length=1000), nullable=True),
        sa.Column("objectif_principal", sa.String(length=1000), nullable=True),
        sa.Column("poids_actuel", sa.String(length=1000), nullable=True),
        sa.Column("taille_cm", sa.String(length=1000), nullable=True),
        sa.Column("type_abonnement", sa.String(length=1000), nullable=True),
        sa.Column("date_inscription", sa.String(length=1000), nullable=True),
        sa.Column("mot_de_passe_hash", sa.String(length=1000), nullable=True),
        sa.Column("erreur", sa.Text(), nullable=False),
        sa.Column(
            "est_corrige", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "date_import",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_utilisateur_import_anomalies_id"),
        "utilisateur_import_anomalies",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_utilisateur_import_anomalies_id"),
        table_name="utilisateur_import_anomalies",
    )
    op.drop_table("utilisateur_import_anomalies")
    op.drop_index(
        op.f("ix_exercice_import_anomalies_id"), table_name="exercice_import_anomalies"
    )
    op.drop_table("exercice_import_anomalies")
    op.drop_index(
        op.f("ix_aliment_import_anomalies_id"), table_name="aliment_import_anomalies"
    )
    op.drop_table("aliment_import_anomalies")
    # ### end Alembic commands ###
