"""Modif limit type pourcentage_gras Numeric(5, 1)

Revision ID: 7a750fef47b6
Revises: 23df462e9ef6
Create Date: 2026-04-09 21:50:42.620586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a750fef47b6'
down_revision: Union[str, Sequence[str], None] = '23df462e9ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_historique_seance_exercice', 'pourcentage_gras',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_historique_seance_exercice', 'pourcentage_gras',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
