"""Initial migration

Revision ID: ad126df3a10e
Revises:
Create Date: 2026-04-15 18:12:27.104180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad126df3a10e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aliment",
        sa.Column("id_aliment", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("categorie", sa.String(length=100), nullable=True),
        sa.Column("type_repas", sa.String(length=50), nullable=True),
        sa.Column("calories", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("proteines", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("lipides", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("glucides", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("fibres", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("sucres", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("sodium_mg", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("cholesterol_mg", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("eau_ml", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column(
            "unite_mesure",
            sa.String(length=50),
            server_default="portion",
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id_aliment"),
    )
    op.create_index(
        op.f("ix_aliment_id_aliment"), "aliment", ["id_aliment"], unique=False
    )
    op.create_table(
        "dataset_historique_seance_exercice",
        sa.Column(
            "id_dataset_historique_seance_exercice", sa.Integer(), nullable=False
        ),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("sexe", sa.String(length=50), nullable=True),
        sa.Column("poids_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("taille_cm", sa.Integer(), nullable=True),
        sa.Column("bpm_max", sa.Integer(), nullable=True),
        sa.Column("bpm_moyen", sa.Integer(), nullable=True),
        sa.Column("bpm_repos", sa.Integer(), nullable=True),
        sa.Column(
            "duree_seance_minutes", sa.Numeric(precision=5, scale=1), nullable=True
        ),
        sa.Column("calories_brulees", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("type_sport", sa.String(length=100), nullable=True),
        sa.Column("pourcentage_gras", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column(
            "consommation_eau_ml", sa.Numeric(precision=8, scale=2), nullable=True
        ),
        sa.Column("frequence_sport_jour_semaine", sa.Integer(), nullable=True),
        sa.Column("niveau_experience", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_dataset_historique_seance_exercice"),
    )
    op.create_index(
        op.f(
            "ix_dataset_historique_seance_exercice_id_dataset_historique_seance_exercice"
        ),
        "dataset_historique_seance_exercice",
        ["id_dataset_historique_seance_exercice"],
        unique=False,
    )
    op.create_table(
        "dataset_recommendations_regime",
        sa.Column("id_dataset_recommendations_regime", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("sexe", sa.String(length=50), nullable=True),
        sa.Column("poids_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("taille_cm", sa.Integer(), nullable=True),
        sa.Column("type_maladie", sa.String(length=255), nullable=True),
        sa.Column("gravite", sa.String(length=50), nullable=True),
        sa.Column("niveau_activite_physique", sa.String(length=100), nullable=True),
        sa.Column("apport_calorique_journalier", sa.Integer(), nullable=True),
        sa.Column("cholesterol_mg_dl", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "tension_arterielle_mmHg", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("glucose_mg_dl", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("restrictions_alimentaires", sa.String(length=255), nullable=True),
        sa.Column("allergies", sa.String(length=255), nullable=True),
        sa.Column("cuisine_preferee", sa.String(length=100), nullable=True),
        sa.Column(
            "heures_exercice_semaine", sa.Numeric(precision=4, scale=2), nullable=True
        ),
        sa.Column("adherence_regime", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "score_desiquilibre_nutriment",
            sa.Numeric(precision=4, scale=1),
            nullable=True,
        ),
        sa.Column("recommendation_regime", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id_dataset_recommendations_regime"),
    )
    op.create_index(
        op.f("ix_dataset_recommendations_regime_id_dataset_recommendations_regime"),
        "dataset_recommendations_regime",
        ["id_dataset_recommendations_regime"],
        unique=False,
    )
    op.create_table(
        "etl_log",
        sa.Column("id_etl_log", sa.Integer(), nullable=False),
        sa.Column("libelle_pipeline", sa.String(length=255), nullable=False),
        sa.Column("fichier_nom", sa.String(length=255), nullable=False),
        sa.Column(
            "date_execution",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("nb_lignes_total", sa.Integer(), nullable=True),
        sa.Column("nb_lignes_valides", sa.Integer(), nullable=True),
        sa.Column("nb_lignes_anomalies", sa.Integer(), nullable=True),
        sa.Column(
            "statut",
            sa.Enum(
                "PENDING", "SUCCESS", "PARTIAL_FAILURE", "FAILURE", name="statutetlenum"
            ),
            nullable=True,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id_etl_log"),
    )
    op.create_index(
        op.f("ix_etl_log_id_etl_log"), "etl_log", ["id_etl_log"], unique=False
    )
    op.create_table(
        "exercice",
        sa.Column("id_exercice", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=150), nullable=False),
        sa.Column("type_exercice", sa.String(length=100), nullable=False),
        sa.Column("muscles_principaux", sa.String(length=100), nullable=True),
        sa.Column("muscles_secondaires", sa.String(length=100), nullable=True),
        sa.Column("equipement", sa.String(length=100), nullable=True),
        sa.Column("difficulte", sa.String(length=50), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id_exercice"),
    )
    op.create_index(
        op.f("ix_exercice_id_exercice"), "exercice", ["id_exercice"], unique=False
    )
    op.create_table(
        "utilisateur",
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=50), nullable=False),
        sa.Column("prenom", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("date_de_naissance", sa.Date(), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("mot_de_passe_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "type_abonnement",
            sa.String(length=50),
            server_default="Freemium",
            nullable=True,
        ),
        sa.Column(
            "date_inscription",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id_utilisateur"),
    )
    op.create_index(op.f("ix_utilisateur_email"), "utilisateur", ["email"], unique=True)
    op.create_index(
        op.f("ix_utilisateur_id_utilisateur"),
        "utilisateur",
        ["id_utilisateur"],
        unique=False,
    )
    op.create_table(
        "log_aliment",
        sa.Column("id_log_aliment", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("repas", sa.String(length=50), nullable=False),
        sa.Column("quantite", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("unite", sa.String(length=20), server_default="g", nullable=True),
        sa.Column("id_aliment", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_aliment"],
            ["aliment.id_aliment"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"], ["utilisateur.id_utilisateur"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_log_aliment"),
    )
    op.create_index(
        op.f("ix_log_aliment_id_log_aliment"),
        "log_aliment",
        ["id_log_aliment"],
        unique=False,
    )
    op.create_table(
        "log_sante",
        sa.Column("id_log_sante", sa.Integer(), nullable=False),
        sa.Column(
            "date_log",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("poids_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("pourcentage_gras", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("imc_actuel", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("bpm_repos", sa.Integer(), nullable=True),
        sa.Column("bpm_moyen_journee", sa.Integer(), nullable=True),
        sa.Column("heures_sommeil", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("nb_pas", sa.Integer(), nullable=True),
        sa.Column("hydratation_ml", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"], ["utilisateur.id_utilisateur"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_log_sante"),
    )
    op.create_index(
        op.f("ix_log_sante_id_log_sante"), "log_sante", ["id_log_sante"], unique=False
    )
    op.create_table(
        "log_seance",
        sa.Column("id_seance_log", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("type_seance", sa.String(length=50), nullable=True),
        sa.Column("duree_minutes", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("calorie_brulee", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("bpm_moyen", sa.Integer(), nullable=True),
        sa.Column("id_exercice", sa.Integer(), nullable=True),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_exercice"],
            ["exercice.id_exercice"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"], ["utilisateur.id_utilisateur"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_seance_log"),
    )
    op.create_index(
        op.f("ix_log_seance_id_seance_log"),
        "log_seance",
        ["id_seance_log"],
        unique=False,
    )
    op.create_table(
        "profil_sante",
        sa.Column("id_profil", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=True),
        sa.Column("poids_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("taille_cm", sa.Integer(), nullable=False),
        sa.Column("imc", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("type_maladie", sa.String(length=255), nullable=True),
        sa.Column("severite", sa.String(length=50), nullable=True),
        sa.Column("restrictions_alimentaires", sa.Text(), nullable=True),
        sa.Column("allergies", sa.Text(), nullable=True),
        sa.Column("objectif_principal", sa.String(length=200), nullable=True),
        sa.Column("experience_sportive", sa.String(length=100), nullable=True),
        sa.Column(
            "heures_entrainement_semaine",
            sa.Numeric(precision=4, scale=1),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id_utilisateur"],
        ),
        sa.PrimaryKeyConstraint("id_profil"),
        sa.UniqueConstraint("id_utilisateur"),
    )
    op.create_index(
        op.f("ix_profil_sante_id_profil"), "profil_sante", ["id_profil"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profil_sante_id_profil"), table_name="profil_sante")
    op.drop_table("profil_sante")
    op.drop_index(op.f("ix_log_seance_id_seance_log"), table_name="log_seance")
    op.drop_table("log_seance")
    op.drop_index(op.f("ix_log_sante_id_log_sante"), table_name="log_sante")
    op.drop_table("log_sante")
    op.drop_index(op.f("ix_log_aliment_id_log_aliment"), table_name="log_aliment")
    op.drop_table("log_aliment")
    op.drop_index(op.f("ix_utilisateur_id_utilisateur"), table_name="utilisateur")
    op.drop_index(op.f("ix_utilisateur_email"), table_name="utilisateur")
    op.drop_table("utilisateur")
    op.drop_index(op.f("ix_exercice_id_exercice"), table_name="exercice")
    op.drop_table("exercice")
    op.drop_index(op.f("ix_etl_log_id_etl_log"), table_name="etl_log")
    op.drop_table("etl_log")
    op.drop_index(
        op.f("ix_dataset_recommendations_regime_id_dataset_recommendations_regime"),
        table_name="dataset_recommendations_regime",
    )
    op.drop_table("dataset_recommendations_regime")
    op.drop_index(
        op.f(
            "ix_dataset_historique_seance_exercice_id_dataset_historique_seance_exercice"
        ),
        table_name="dataset_historique_seance_exercice",
    )
    op.drop_table("dataset_historique_seance_exercice")
    op.drop_index(op.f("ix_aliment_id_aliment"), table_name="aliment")
    op.drop_table("aliment")
    # ### end Alembic commands ###
